export default {
  "0dffb83e": [() => import(/* webpackChunkName: "0dffb83e" */ "@site/docs/roadmap.md"), "@site/docs/roadmap.md", require.resolveWeak("@site/docs/roadmap.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "2b1660b5": [() => import(/* webpackChunkName: "2b1660b5" */ "@site/docs/testiprojekti/api.md"), "@site/docs/testiprojekti/api.md", require.resolveWeak("@site/docs/testiprojekti/api.md")],
  "33c29366": [() => import(/* webpackChunkName: "33c29366" */ "@site/docs/testiprojekti/kaytto.md"), "@site/docs/testiprojekti/kaytto.md", require.resolveWeak("@site/docs/testiprojekti/kaytto.md")],
  "3be696df": [() => import(/* webpackChunkName: "3be696df" */ "@site/docs/testiprojekti/intro.md"), "@site/docs/testiprojekti/intro.md", require.resolveWeak("@site/docs/testiprojekti/intro.md")],
  "3fcd3f64": [() => import(/* webpackChunkName: "3fcd3f64" */ "@generated/docusaurus-plugin-content-docs/default/p/testiprojekti-docs-36b.json"), "@generated/docusaurus-plugin-content-docs/default/p/testiprojekti-docs-36b.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/testiprojekti-docs-36b.json")],
  "5281b7a2": [() => import(/* webpackChunkName: "5281b7a2" */ "@site/docs/architecture.md"), "@site/docs/architecture.md", require.resolveWeak("@site/docs/architecture.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "9beb87c2": [() => import(/* webpackChunkName: "9beb87c2" */ "@site/docs/changelog.md"), "@site/docs/changelog.md", require.resolveWeak("@site/docs/changelog.md")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "ae4554eb": [() => import(/* webpackChunkName: "ae4554eb" */ "@site/docs/vision.md"), "@site/docs/vision.md", require.resolveWeak("@site/docs/vision.md")],
  "c377a04b": [() => import(/* webpackChunkName: "c377a04b" */ "@site/docs/index.md"), "@site/docs/index.md", require.resolveWeak("@site/docs/index.md")],
  "e8ef842d": [() => import(/* webpackChunkName: "e8ef842d" */ "@site/docs/video_demo_material.md"), "@site/docs/video_demo_material.md", require.resolveWeak("@site/docs/video_demo_material.md")],};
